package com.example.ui.util

import android.content.Context
import android.content.Intent
import androidx.core.content.FileProvider
import com.example.data.DailyScheduleView
import com.example.data.IntakeLog
import com.example.data.Medication
import java.io.File
import java.time.LocalDate
import java.time.format.DateTimeFormatter

object ReportExportHelper {

    fun generateAndShareReport(
        context: Context,
        userAccountName: String,
        userEmail: String,
        medications: List<Medication>,
        schedules: List<DailyScheduleView>,
        todayLogs: List<IntakeLog>,
        streakDays: Int
    ) {
        val dateStr = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"))
        val builder = StringBuilder()

        builder.append("=========================================\n")
        builder.append("         MEDITRACKER HEALTH REPORT       \n")
        builder.append("=========================================\n")
        builder.append("Generated Date: $dateStr\n")
        builder.append("Patient / User: ${userAccountName.ifBlank { "Guest User" }}\n")
        if (userEmail.isNotBlank()) {
            builder.append("Email Account: $userEmail\n")
        }
        builder.append("Adherence Streak: $streakDays days compliant\n\n")

        builder.append("--- ACTIVE MEDICATIONS (${medications.size}) ---\n")
        if (medications.isEmpty()) {
            builder.append("No active medications listed.\n")
        } else {
            medications.forEachIndexed { index, med ->
                builder.append("${index + 1}. ${med.name} (${med.dosage})\n")
                if (med.notes.isNotBlank()) builder.append("   Notes: ${med.notes}\n")
                builder.append("   Frequency: ${med.timesPerDay} time(s) per day\n")
                builder.append("   Stock Remaining: ${med.stockCount} pills (Low Stock Refill Level: ${med.lowStockThreshold})\n")
                builder.append("\n")
            }
        }

        builder.append("--- TODAY'S INTAKE LOGS (${todayLogs.size}/${schedules.size}) ---\n")
        if (schedules.isEmpty()) {
            builder.append("No scheduled doses for today.\n")
        } else {
            schedules.forEach { sch ->
                val isTaken = todayLogs.any { it.scheduleId == sch.scheduleId }
                val timeFormatted = String.format("%02d:%02d", sch.timeHour, sch.timeMinute)
                val status = if (isTaken) "✓ TAKEN" else "✗ PENDING"
                builder.append("• $timeFormatted - ${sch.name} (${sch.dosage}) -> $status\n")
            }
        }

        builder.append("\n=========================================\n")
        builder.append("Generated by PillTracker App\n")

        val reportText = builder.toString()

        try {
            val reportFile = File(context.cacheDir, "PillTracker_Report_$dateStr.txt")
            reportFile.writeText(reportText)

            val fileUri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                reportFile
            )

            val sendIntent = Intent().apply {
                action = Intent.ACTION_SEND
                putExtra(Intent.EXTRA_SUBJECT, "PillTracker Medical Report - ${userAccountName.ifBlank { "Patient" }} ($dateStr)")
                putExtra(Intent.EXTRA_TEXT, reportText)
                putExtra(Intent.EXTRA_STREAM, fileUri)
                type = "text/plain"
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }

            val shareIntent = Intent.createChooser(sendIntent, "Share Medical Report")
            context.startActivity(shareIntent)
        } catch (e: Exception) {
            e.printStackTrace()
            // Direct text fallback
            val sendIntent = Intent().apply {
                action = Intent.ACTION_SEND
                putExtra(Intent.EXTRA_SUBJECT, "PillTracker Medical Report - ${userAccountName.ifBlank { "Patient" }} ($dateStr)")
                putExtra(Intent.EXTRA_TEXT, reportText)
                type = "text/plain"
            }
            context.startActivity(Intent.createChooser(sendIntent, "Share Medical Report"))
        }
    }
}

