package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// 1. Light Theme Palette (Crisp Clean Slate & Teal)
val LightBackground = Color(0xFFF8FAFC)
val LightOnBackground = Color(0xFF0F172A)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF0F172A)
val LightSurfaceVariant = Color(0xFFF1F5F9)
val LightOnSurfaceVariant = Color(0xFF475569)
val LightPrimary = Color(0xFF0F766E)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFCCFBF1)
val LightOnPrimaryContainer = Color(0xFF0F514C)
val LightOutline = Color(0xFFE2E8F0)
val LightOutlineVariant = Color(0xFFCBD5E1)

// 2. Telegram Dark Theme Palette (Authentic Midnight Blue/Gray)
val TelegramDarkBackground = Color(0xFF0F141D)
val TelegramDarkOnBackground = Color(0xFFF5F5F5)
val TelegramDarkSurface = Color(0xFF17212B)
val TelegramDarkOnSurface = Color(0xFFF5F5F5)
val TelegramDarkSurfaceVariant = Color(0xFF242F3D)
val TelegramDarkOnSurfaceVariant = Color(0xFF8E9DAE)
val TelegramDarkPrimary = Color(0xFF5288C1)
val TelegramDarkOnPrimary = Color(0xFFFFFFFF)
val TelegramDarkPrimaryContainer = Color(0xFF1E2C3A)
val TelegramDarkOnPrimaryContainer = Color(0xFF80B3E6)
val TelegramDarkOutline = Color(0xFF2B394A)
val TelegramDarkOutlineVariant = Color(0xFF1E293B)

// 3. Brand Signature Theme Palette (Luxurious Deep Emerald & Mint)
val BrandBackground = Color(0xFF041A17)
val BrandOnBackground = Color(0xFFECFDF5)
val BrandSurface = Color(0xFF092C27)
val BrandOnSurface = Color(0xFFECFDF5)
val BrandSurfaceVariant = Color(0xFF11423B)
val BrandOnSurfaceVariant = Color(0xFF99F6E4)
val BrandPrimary = Color(0xFF2DD4BF)
val BrandOnPrimary = Color(0xFF003832)
val BrandPrimaryContainer = Color(0xFF0F766E)
val BrandOnPrimaryContainer = Color(0xFFCCFBF1)
val BrandOutline = Color(0xFF134E4A)
val BrandOutlineVariant = Color(0xFF1E6B62)


