package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// 1. Light Theme Palette (Crisp Modern Slate & Vibrant Emerald Teal)
val LightBackground = Color(0xFFF8FAFC)
val LightOnBackground = Color(0xFF0F172A)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF0F172A)
val LightSurfaceVariant = Color(0xFFF1F5F9)
val LightOnSurfaceVariant = Color(0xFF475569)
val LightPrimary = Color(0xFF0D9488)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFCCFBF1)
val LightOnPrimaryContainer = Color(0xFF115E59)
val LightSecondary = Color(0xFF0284C7)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFE0F2FE)
val LightOnSecondaryContainer = Color(0xFF0369A1)
val LightTertiary = Color(0xFF8B5CF6)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFEDE9FE)
val LightOnTertiaryContainer = Color(0xFF6D28D9)
val LightError = Color(0xFFDC2626)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFEE2E2)
val LightOnErrorContainer = Color(0xFF991B1B)
val LightOutline = Color(0xFFCBD5E1)
val LightOutlineVariant = Color(0xFFE2E8F0)

// 2. Telegram AMOLED Pure Dark Theme Palette (Pure Pitch Black & Vivid Azure Cyan)
val TelegramDarkBackground = Color(0xFF090D14)
val TelegramDarkOnBackground = Color(0xFFF8FAFC)
val TelegramDarkSurface = Color(0xFF151C28)
val TelegramDarkOnSurface = Color(0xFFF8FAFC)
val TelegramDarkSurfaceVariant = Color(0xFF222C3D)
val TelegramDarkOnSurfaceVariant = Color(0xFFA6B4C9)
val TelegramDarkPrimary = Color(0xFF38BDF8)
val TelegramDarkOnPrimary = Color(0xFF001E2B)
val TelegramDarkPrimaryContainer = Color(0xFF0C3D5E)
val TelegramDarkOnPrimaryContainer = Color(0xFFBAE6FD)
val TelegramDarkSecondary = Color(0xFF38BDF8)
val TelegramDarkOnSecondary = Color(0xFF001E2B)
val TelegramDarkSecondaryContainer = Color(0xFF193549)
val TelegramDarkOnSecondaryContainer = Color(0xFFBAE6FD)
val TelegramDarkTertiary = Color(0xFFA78BFA)
val TelegramDarkOnTertiary = Color(0xFF2E1065)
val TelegramDarkTertiaryContainer = Color(0xFF4C1D95)
val TelegramDarkOnTertiaryContainer = Color(0xFFDDD6FE)
val TelegramDarkOutline = Color(0xFF475569)
val TelegramDarkOutlineVariant = Color(0xFF334155)
val TelegramDarkError = Color(0xFFF87171)
val TelegramDarkOnError = Color(0xFF450A0A)
val TelegramDarkErrorContainer = Color(0xFF7F1D1D)
val TelegramDarkOnErrorContainer = Color(0xFFFECACA)

// 3. Brand Signature Pure Dark Emerald Theme Palette
val BrandBackground = Color(0xFF061210)
val BrandOnBackground = Color(0xFFECFDF5)
val BrandSurface = Color(0xFF0F2622)
val BrandOnSurface = Color(0xFFF0FDF4)
val BrandSurfaceVariant = Color(0xFF1A3B35)
val BrandOnSurfaceVariant = Color(0xFF99F6E4)
val BrandPrimary = Color(0xFF2DD4BF)
val BrandOnPrimary = Color(0xFF003832)
val BrandPrimaryContainer = Color(0xFF115E54)
val BrandOnPrimaryContainer = Color(0xFFCCFBF1)
val BrandSecondary = Color(0xFF2DD4BF)
val BrandOnSecondary = Color(0xFF003832)
val BrandSecondaryContainer = Color(0xFF134E46)
val BrandOnSecondaryContainer = Color(0xFFCCFBF1)
val BrandTertiary = Color(0xFFA78BFA)
val BrandOnTertiary = Color(0xFF2E1065)
val BrandTertiaryContainer = Color(0xFF4C1D95)
val BrandOnTertiaryContainer = Color(0xFFDDD6FE)
val BrandOutline = Color(0xFF336B60)
val BrandOutlineVariant = Color(0xFF245249)
val BrandError = Color(0xFFF87171)
val BrandOnError = Color(0xFF450A0A)
val BrandErrorContainer = Color(0xFF7F1D1D)
val BrandOnErrorContainer = Color(0xFFFECACA)



